[tools]
deno = "2.5.6"
node = "24.11.1"
"npm:@angular/cli" = "21.0.0"
"npm:@google/gemini-cli" = "0.17.1"
"npm:@hono/cli" = "0.1.0"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.63.0"
"npm:ccusage" = "17.1.6"
"npm:pnpm" = "10.23.0"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.85"
python = "3.14.0"
swiftlint = "0.62.2"
uv = "0.9.11"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
compile = false
