[tools]
deno = "2.6.3"
fzf = "0.67.0"
ghq = "1.8.0"
go = "1.25.5"
node = "24.12.0"
"npm:@angular/cli" = "21.0.4"
"npm:@dotenvx/dotenvx" = "1.51.2"
"npm:@google/gemini-cli" = "0.22.2"
"npm:@hono/cli" = "0.1.6"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.77.0"
"npm:ccusage" = "17.2.0"
"npm:pnpm" = "10.26.1"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
python = "3.14.2"
swiftlint = "0.62.2"
uv = "0.9.18"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
compile = false
