[tools]
deno = "2.6.4"
fzf = "0.67.0"
ghq = "1.8.0"
go = "1.25.5"
node = "24.12.0"
"npm:@angular/cli" = "21.0.5"
"npm:@dotenvx/dotenvx" = "1.51.4"
"npm:@google/gemini-cli" = "0.23.0"
"npm:@hono/cli" = "0.1.6"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.79.0"
"npm:ccusage" = "17.2.1"
"npm:pnpm" = "10.27.0"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
python = "3.14.2"
swiftlint = "0.63.0"
uv = "0.9.24"
zellij = "0.43.1"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
compile = false
