[tools]
bun = "1.3.9"
deno = "2.6.9"
fzf = "0.67.0"
gleam = "1.14.0"
go = "1.26.0"
node = "24.13.1"
"npm:@angular/cli" = "21.1.4"
"npm:@ionic/cli" = "7.2.1"
"npm:@playwright/cli" = "0.1.0"
"npm:agent-browser" = "0.9.2"
"npm:ccusage" = "18.0.5"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.95"
pnpm = "10.29.3"
python = "3.14.3"
swiftlint = "0.63.2"
uv = "0.10.2"
xh = "0.25.3"
zellij = "0.43.1"

[settings]
lockfile = true
