[tools]
deno = "2.6.5"
fzf = "0.67.0"
ghq = "1.8.0"
go = "1.25.5"
node = "24.13.0"
"npm:@angular/cli" = "21.0.5"
"npm:@dotenvx/dotenvx" = "1.51.4"
"npm:@hono/cli" = "0.1.8"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.80.0"
"npm:agent-browser" = "0.4.4"
"npm:ccusage" = "18.0.5"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
pnpm = "10.28.0"
python = "3.14.2"
swiftlint = "0.63.0"
uv = "0.9.25"
zellij = "0.43.1"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
compile = false
