[tools]
bun = "1.3.10"
deno = "2.7.1"
fzf = "0.67.0"
ghq = "1.9.3"
go = "1.26.0"
node = "24.14.0"
"npm:@angular/cli" = "21.2.0"
"npm:@ionic/cli" = "7.2.1"
"npm:@playwright/cli" = "0.1.1"
"npm:agent-browser" = "0.15.1"
"npm:ccusage" = "18.0.8"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.1.10"
pnpm = "10.30.3"
python = "3.14.3"
swiftlint = "0.63.2"
uv = "0.10.7"
xh = "0.25.3"
zellij = "0.43.1"

[settings]
lockfile = true
