[tools]
bun = "1.3.8"
deno = "2.6.8"
fzf = "0.67.0"
go = "1.25.7"
node = "24.13.0"
"npm:@angular/cli" = "21.1.2"
"npm:@dotenvx/dotenvx" = "1.52.0"
"npm:@hono/cli" = "0.1.10"
"npm:@ionic/cli" = "7.2.1"
"npm:@playwright/cli" = "0.0.62"
"npm:agent-browser" = "0.8.6"
"npm:ccusage" = "18.0.5"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
pnpm = "10.28.2"
python = "3.14.3"
swiftlint = "0.63.2"
uv = "0.9.29"
xh = "0.25.3"
zellij = "0.43.1"

[settings]

[settings.npm]
package_manager = "bun"
