[tools]
deno = "2.6.6"
fzf = "0.67.0"
ghq = "1.8.0"
go = "1.25.6"
neovim = "0.11.6"
node = "24.13.0"
"npm:@angular/cli" = "21.1.1"
"npm:@dotenvx/dotenvx" = "1.52.0"
"npm:@hono/cli" = "0.1.8"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.89.0"
"npm:agent-browser" = "0.7.6"
"npm:ccusage" = "18.0.5"
"npm:tree-sitter-cli" = "0.26.3"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
pnpm = "10.28.1"
python = "3.14.2"
swiftlint = "0.63.2"
uv = "0.9.27"
xh = "0.25.3"
zellij = "0.43.1"
