[tools]
deno = "2.6.0"
ghq = "1.8.0"
go = "1.25.5"
node = "24.12.0"
"npm:@angular/cli" = "21.0.2"
"npm:@dotenvx/dotenvx" = "1.51.1"
"npm:@google/gemini-cli" = "0.19.4"
"npm:@hono/cli" = "0.1.3"
"npm:@ionic/cli" = "7.2.1"
"npm:@openai/codex" = "0.66.0"
"npm:ccusage" = "17.1.8"
"npm:pnpm" = "10.25.0"
pipx = "1.8.0"
"pipx:git+https://github.com/github/spec-kit.git" = "v0.0.90"
python = "3.14.2"
swiftlint = "0.62.2"
uv = "0.9.17"

[env]

[settings]
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
compile = false
